apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      run: java-app
  replicas: 1
  template:
    metadata:
      labels:
        run: java-app
    spec:
      containers:
      - name: java-app
        image: aleks9001/java_app:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: java-app
spec:
  type: LoadBalancer
  selector:
    run: java-app
  ports:
    - nodePort: 32542
      protocol: TCP
      port: 8080
      targetPort: 8080
# status:
#   loadBalancer:
#     ingress:
#     - ip: 35.198.136.180

---

apiVersion: v1
kind: Service
metadata:
  name: java-app
  labels:
    run: java-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: java-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: api.k.devops.sportal365.dev
    http:
      paths:
      - backend:
          service:
            name: java-app
            servicePort: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.k.devops.sportal365.dev
    secretName: api-ingress-tls

---
